#!/command/with-contenv sh
export HOME=/home/user
export DISPLAY=${DISPLAY:-:99}
exec s6-setuidgid user chromium --start-maximized --no-sandbox --remote-debugging-port=9221 --disable-dev-shm-usage --user-data-dir=/home/user/chrome-profile --proxy-server=http://127.0.0.1:8119 duck.com
